# mybatis-plus 配置
mybatis-plus:
    mapper-locations: /mapper/**.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    type-aliases-package: top.playereg.pix_vision.pojo
    global-config:
        banner: false
    type-handlers-package: top.playereg.pix_vision.handler