workspace-name: .pix_vision # 工作空间名称
server:
    port: 9090
    forward-headers-strategy: native # 启动时使用SpringBoot内置的Tomcat

spring:
    config:
        import: # 引入配置文件
            - classpath:config/email.yml
            - classpath:config/jdbc.yml
            - classpath:config/redis.yml
            - classpath:config/mybatis-plus.yml
            - classpath:config/pix_vision.yml
            - classpath:config/spring-doc.yml
            - classpath:config/logging.yml
            - optional:file:${user.home}/${workspace-name}/application.yml
    devtools:
        restart:
            enabled: false # 禁用热部署
    main:
        banner-mode: console
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    application:
        name: PixVision  # 服务名称
        version: DEV-2.0.0

