workspace-name: .pix_vision # 工作空间名称
python-server:
  base-url: http://localhost:8000/api/v1

server:
  port: 9090
  forward-headers-strategy: native # 启动时使用SpringBoot内置的Tomcat

spring:
  config:
    import: # 引入配置文件
      - classpath:yml-config/email.yml # 邮件
      - classpath:yml-config/jdbc.yml # jdbc
      - classpath:yml-config/redis.yml # redis
      - classpath:yml-config/mybatis-plus.yml # mybatis-plus
      - classpath:yml-config/spring-doc.yml # 文档
      - classpath:yml-config/logging.yml # 日志
      - classpath:yml-config/cors.yml # 跨域
      - classpath:yml-config/log-output.yml # 日志输出
      - classpath:yml-config/pix_vision.yml # 系统配置文件
      - classpath:yml-config/spring-core.yml # Spring 核心配置
      - optional:file:${user.home}/${workspace-name}/application.yml # 用户自定义配置文件
